import{a as E,S,i as u}from"./assets/vendor-DqB7j7Ix.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const v="50872380-a1850de8631dfd470b651c05b",q="https://pixabay.com/api/",w=15;async function m(o,t=1){return(await E.get(q,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:w}})).data}const P=new S(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function f(o){const t=document.querySelector(".gallery"),l=o.map(({webformatURL:c,largeImageURL:e,tags:r,likes:a,views:_,comments:L,downloads:b})=>`
    <li class="gallery__item">
      <a class="gallery__link" href="${e}">
        <img class="gallery__image" src="${c}" alt="${r}" loading="lazy"/>
        <div class="gallery__info">
        <p class="gallery__text"><b>Likes</b><span>${a}</span></p>
        <p class="gallery__text"><b>Views</b><span>${_}</span></p>
        <p class="gallery__text"><b>Comments</b><span>${L}</span></p>
        <p class="gallery__text"><b>Downloads</b><span>${b}</span></p>
        </div>
      </a>
    </li>`).join("");t.insertAdjacentHTML("beforeend",l),P.refresh()}function $(){document.querySelector(".gallery").innerHTML=""}function y(){document.querySelector(".loader-container").classList.remove("hidden")}function p(){document.querySelector(".loader-container").classList.add("hidden")}function g(){document.querySelector(".load-more").classList.remove("is-hidden")}function i(){document.querySelector(".load-more").classList.add("is-hidden")}const x=document.getElementById("search-form"),B=document.querySelector(".load-more"),M=document.querySelector(".gallery");i();let n="",s=1,d=0;const h=15;x.addEventListener("submit",A);B.addEventListener("click",O);async function A(o){if(o.preventDefault(),n=o.currentTarget.searchQuery.value.trim(),!!n){s=1,$(),i();try{y();const t=await m(n,s);if(d=t.totalHits,d===0){u.error({title:"😕 No images",message:`No results for "${n}"`}),i();return}f(t.hits),s*h<d&&g()}catch(t){u.error({title:"Error",message:t.message})}finally{p()}}}async function O(){s++,i();try{y();const o=await m(n,s);f(o.hits);const{height:t}=M.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),s*h>=d?(u.info({title:"We're sorry",message:"You've reached the end of search results."}),i()):g()}catch(o){u.error({title:"Error",message:o.message})}finally{p()}}
//# sourceMappingURL=index.js.map
